@startuml
participant User
participant ":Ui" as Ui

box "Logic" #LightBlue
participant ":LogicManager" as LogicManager
participant ":Parser" as Parser
participant "command:MarkCommand" as MarkCommand
participant "result:CommandResult" as CommandResult
end box

box "Model" #LightPink
participant ":ModelManager" as ModelManager
participant ":ModuleList" as ModuleList
participant "module:Module" as Module
end box


User -> Ui: getUserCommand() "mark CS2113 g/A+"
activate Ui

Ui -> LogicManager: getCommand()
activate LogicManager

LogicManager -> Parser: parseCommand()
activate Parser

create MarkCommand
Parser -> MarkCommand
activate MarkCommand

MarkCommand --> Parser: command
deactivate MarkCommand


Parser --> LogicManager: command
deactivate Parser


LogicManager -> MarkCommand: execute()
activate MarkCommand


MarkCommand -> ModelManager: getModuleList()
activate ModelManager
ModelManager --> MarkCommand: index
deactivate ModelManager

MarkCommand -> ModelManager: markModule(i)
activate ModelManager

ModelManager -> ModuleList: getModule(i)
activate ModuleList

ModuleList --> ModelManager: module
deactivate ModuleList

ModelManager -> Module: markModule(i, grade)
activate Module
Module -> Module: Mark()

Module --> ModelManager
deactivate Module

ModelManager --> MarkCommand
deactivate ModelManager

create CommandResult


MarkCommand -> CommandResult
activate CommandResult
CommandResult --> MarkCommand
deactivate CommandResult
destroy CommandResult

MarkCommand --> LogicManager: result
deactivate MarkCommand
destroy MarkCommand

LogicManager --> Ui: printResult()
deactivate LogicManager

Ui --> User
deactivate Ui

@enduml