@startuml
participant User

create Ui
activate Ui
User -> Ui: getUserCommand() "plan CS2113 y/1 s/2"

Ui -> LogicManager: getCommand()
activate LogicManager


LogicManager -> Parser: parseCommand()
activate Parser


create PlanCommand
Parser -> PlanCommand
activate PlanCommand

PlanCommand --> Parser: PlanCommand()
deactivate PlanCommand


Parser --> LogicManager: Command()
deactivate Parser


LogicManager -> PlanCommand: execute()
activate PlanCommand

PlanCommand -> ModelManager: addModule()
activate ModelManager

ModelManager -> ModuleList: addModule()
activate ModuleList

ModuleList -> ModuleList: add()

ModuleList --> ModelManager: 
deactivate ModuleList

ModelManager --> PlanCommand
deactivate ModelManager

PlanCommand --> LogicManager: CommandResult()
deactivate PlanCommand

LogicManager --> Ui: printResult()
deactivate LogicManager

Ui --> User
deactivate Ui

@enduml